name: Xshards
version: 1.2.2
main: com.xshards.Xshards
api-version: 1.17

commands:
  shards:
    description: Check your shard balance
    usage: /<command>
  store:
    description: Access the shard shop
    usage: /<command> [edit <slot> <price>]
  afk:
    description: Set yourself as AFK
    usage: /<command>
  setafk:
    description: Set your AFK location
    usage: /<command>
  quitafk:
    description: Quit AFK mode
    usage: /<command>
  afkremove:
    description: Remove your AFK location
    usage: /<command>
  xshards:
    description: Plugin management commands
    usage: /<command> [reload|help]

permissions:
  xshards.use:
    description: Allows access to shard and AFK commands
    default: true
  xshards.admin:
    description: Allows access to admin commands for managing the shop and AFK locations
    default: op

softdepend:
  - PlaceholderAPI
  - Multiverse-Core